Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.network :private_network, ip: '192.168.56.10'

  config.vm.provider "virtualbox" do |vb|

      vb.name = "Ubuntu"
      vb.cpus = 1
      vb.memory = 1024
      vb.gui = false

  end

end