- name: Test
  hosts: all
  become: True
  become_user: root

  tasks:
  - name: Deploy SSH Public Key
    authorized_key:
      user: vagrant
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      

  
